### PR TITLE
got rid of isJSON and parse instead

### PR DESCRIPTION
**Pull request by coderextreme**
Please test this with dataURLs and XML inlines.  I tested the JSON.

### CODE REVIEW

**Comment by coderextreme** [comment]
x3d inlines work

**Comment by andreasplesch** [comment]
Does JSON.parse fail immediately on a xml format response ? Presumably yes but can you confirm, please ?

Also the PR currently only has Inline.js, nothing else. It may work to just create a new branch from coderextreme:master and create a PR then from this branch. Then I can test.

**Comment by coderextreme** [comment]
i don’t know about immediately, but i tried an xml fie and it fell through.  I’ll look into creating a new branch and a PR, but I’m socializing with my wife right now.  You can also do a PR from my repo, coderextreme/x3dom.

John

**Comment by andreasplesch** [comment]
No rush ;) .

**Comment by andreasplesch** [comment]
I tried to create a PR from your repo but your master branch does not have the JSON parser anymore ?

**Comment by coderextreme** [comment]
My local master has it. How do I push my local master to remote again, overwriting?

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
Okay, this is getting scary.  In order to do a push, I have to fetch first, which will overwrite local.  I’ll make a backup.

John

Sent from Mail for Windows 10

From: John Carlson
Sent: Thursday, May 17, 2018 1:38 PM
To: x3dom/x3dom; x3dom/x3dom
Cc: Author
Subject: RE: [x3dom/x3dom] got rid of isJSON and parse instead (#842)

My local master has it. How do I push my local master to remote again, overwriting?

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
I can’t get XML loading working, so I am not checking in Inline.js yet.  The other files should be present.

John

Sent from Mail for Windows 10

**Comment by andreasplesch** [comment]
git push, if everything is set up

**Comment by coderextreme** [comment]
Pull request in place.  There may be a difference in styling in the dev x3dom, FYI, haven’t analyzed it yet.

I was operating with the dev version for a while.

John

Sent from Mail for Windows 10

**Pull request closed without merging**
