### PR TITLE
Add viewpoint and navigation support in webxr

### PR DESCRIPTION
**Pull request by rghv96**

### CODE REVIEW

**Comment by rghv96** [comment]
@andreasplesch @tsturm @msub2

Please review this PR.

**Comment by andreasplesch** [comment]
Could you please start from the current webxr branch, so that only your changes are listed in this or a new PR ?

**Comment by rghv96** [comment]
@andreasplesch I have added the scaleFactor of 0.001 in the fit function in VRControllerManager. Also, I don't fully understand why do we need this function as ideally, we should not need any movement in viewArea when we enter VR mode.

**Comment by andreasplesch** [comment]
I think it was an attempt to automatically have a better view when switching to XR. It may not be needed with viewpoint support. I used the small scale factor only as a safe way to disable the fit function without removing it.

**Comment by rghv96** [comment]
Alright, I think the PR is ready to review @andreasplesch

**Comment by andreasplesch** [comment]
@tsturm and @msub2 ?

**Comment by msub2** [comment]
Apologies for delay, looks good to me though

**Comment by andreasplesch** [comment]
Thanks.

**Pull request merged**
