### PR TITLE
Configuration Documentation updates - added useGeoCache & others

### PR DESCRIPTION
**Pull request by jamesleesaunders**
Updated Scene Author - Configuration documentation (https://doc.x3dom.org/author/configuration.html):
  * Added new useGeoCache option added by #968.
  * Fixed a couple of missing closing html tags + typo + quick run though prettifier.
  * Also added a number of other missing config parameters found in Main.js - I need some help to fill in some of the ?? gaps as some of these I don't know what they do?

While doing this I noticed the now deprecated options 'flashrenderer' and 'swfpath' were no longer referenced anywhere in code, so I have removed these from the Main.js validParams list.

### CODE REVIEW

**Comment by jamesleesaunders** [comment]
On top of the additional useGeoCache option, these are the others I have added which I could do with some help to embellish the docs a little more, descriptions, defaults etc:
* disableDoubleClick
* disableTouch
* disableKeys
* showTouchpoints
* components
* loadpath
* backend
* altImg
* runtimeEnabled
* maxActiveDownloads

**Comment by jamesleesaunders** [comment]
Ahh, thanks @tsturm 
But before this was merged in it really needed some of the ??’s gaps filling in on the docs.
Perhaps you can embellish them in these gaps in subsequent diff?

**Comment by jamesleesaunders** [comment]
What is the process to get these documentation updates pushed to the website?

**Comment by andreasplesch** [comment]
I do not think there is a defined process. It may be a matter of accumulating updates and then asking FHG which maintains the web site to update.

In my fork, I am building and publishing on netlify including the autogenerated docs. Perhaps something similar could be adopted for the main repo.

**Pull request merged**
