### PR TITLE
use glTF node transform tree

### PR DESCRIPTION
**Pull request by andreasplesch**
This PR constructs a world transform for each glTF node and applies it to the node's meshes and their primitives. The world transforms are factored in during updateTransforms where the appropriate shader uniforms are multiplied with the world transform matrixes.
Some uniforms still need to be addressed. 
Discussed in #709

### CODE REVIEW

**Comment by andreasplesch** [comment]
In order to avoid converting transforms for the various uniforms from and to GL format and also avoid a few matrix inversion, it would be more optimal to factor in the node world transforms in gfx_webgl.renderShape, rather than in update Transforms.

The shader parameters there could be recalculated for each of the shape.meshes where these are iterated.

The world transform then could just be kept in a mesh.worldtransform property, rather than material property.

On the other hand gfx_webgl is already long.

**Comment by andreasplesch** [comment]
Ok, I found a mathematical way to avoid additional matrix inversions, eg. keep the existing inversions.

(A x B) ^ -1 = B^-1 x A^-1 (http://mathworld.wolfram.com/MatrixInverse.html)

We want to multiply in the node world transform (B) and can do that by keeping the existing inverse A^-1 and right multiply the inverse of B  which could be precomputed for non-animated nodes.

**Comment by tsturm** [comment]
Thanks Andreas, for this great PR!

**Comment by andreasplesch** [comment]
thanks for merging !
Still missing is to update the picking renderer to also call updateTransforms for glTFs.
Also it would be good to have a getVolume() function for externalShape (similar to externalGeometry).
Are there plans for glTF2 or PBR materials ?

**Comment by andreasplesch** [comment]
missed a few lines while syncing, see #725

**Pull request merged**
