### PR TITLE
Is this how I do a rebase?

### PR DESCRIPTION
**Pull request by coderextreme**

### CODE REVIEW

**Comment by andreasplesch** [comment]
There are no changes in this PR?a

**Comment by andreasplesch** [comment]
Did you want to create a PR in the opposite direction, eg. to update the master branch in your fork?

**Comment by coderextreme** [comment]
What I really want to do is rebase??? or something like that.  Skip forward
local changes to head of main repo.

I've applied changes to my fork from the main development repository (not
mine).   Then there's these empty commits just sitting around.    What I
want the user interface to say is that I am no longer ahead n many
commits.  There are no changes to be applied to the best of my knowledge
(no file differences present).   Perhaps there is an outstanding change?

It's very confusing.

John

**Comment by andreasplesch** [comment]
For a clean history, you can edit a file in rhe x3dom/x3dom master branch with the web interface. It will create a branch patch-1 in your fork which you can use or branch off from.

**Pull request closed without merging**
