### PR TITLE
PointProperties implementation

### PR DESCRIPTION
**Pull request by andreasplesch**

### CODE REVIEW

**Comment by jamesleesaunders** [comment]
Oooo yes! I started this in #1022 but didn’t get very far. And this last year has been a bit mental for me (and us all) to finish it. So glad you have taken this further!
I will have a good play with this as I would love to implement it in d3-x3d.

**Comment by andreasplesch** [comment]
Ok let me merge it in. Tested pretty well but x fingers.

**Comment by andreasplesch** [comment]
An example: https://5f542525f34480000834c7ae--x3dom.netlify.app/examples/cases/points/pointset_archie_normal.html

**Comment by jamesleesaunders** [comment]
Tested with d3-x3d and it works great!
Examples:
  https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X3DOM/chart/ParticlePlot.html
and for comparison the x_ite version:
  https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X_ITE/chart/ParticlePlot.html

(for some reason you have to refresh the page a few times to get the x_ite version to work (and I have had to use x3dom.reload() to get the x3dom version to work)

**Comment by andreasplesch** [comment]
Cool. Just make sure to create the complete Shape outside the Scene first, and then append it. D3 makes this a little difficult but it should be possible.

**Pull request merged**
