### PR TITLE
replaceWorld and JSON functions for Browser [WIP]

### PR DESCRIPTION
**Pull request by coderextreme**
Untested.  Intended for collaborative coding.

### CODE REVIEW

**Comment by andreasplesch** [comment]
This is work in progress.

**Comment by andreasplesch** [comment]
doc._scene is the x3dom node of the scene, not the dom node.

x3dom.reload() works only for new X3D elements (X3D browsers), not for changes within a browser.

**Comment by coderextreme** [comment]
Usage code:
	var element = document.querySelector("#x3delement”);
	if (element.hasRuntime && element.runtime.ready) {
		if ($('#prototype').is(':checked')) {
			var x3d = element.runtime.createX3DFromJS(json, url);
		} else {
			var x3d = element.runtime.createX3DFromJS(json);
		}
		element.runtime.replaceWorld(x3d.querySelector("Scene"));
	}

Not perfect yet.  Need to do x3dom.ready = function…

I will do another pull request.

John
Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
I don't know what else to do beside x3dom.reload() to get the scene to display.  How do I fix replaceWorld?

**Comment by andreasplesch** [comment]
Yeah, I had to go through how x3dom loads the initial scene.

**Comment by coderextreme** [comment]
You missed a close brace.

**Comment by andreasplesch** [comment]
I have merged this into the branch. Just open PRs as needed.

**Comment by andreasplesch** [comment]
I am starting to prefer x3dscene correspond to the x3d element for replaceWorld as well. The x3d element also represents the browser but I think it is closer to the spec.  , and the use pattern is cleaner:
+ *   > element = document.getElementById('the_x3delement');
+ *   > x3d = element.runtime.createX3dFromJS(jsobject, optionalUrl);
+ *   > element.runtime.replaceWorld(x3d);

Functionally, the .querySelector('Scene') would just go into replaceWorld.

**Comment by andreasplesch** [comment]
I opened #855 

https://rawgit.com/x3dom/x3dom/f492fbb9bc19af04c20e580f7f5dad9ecccde0c0/test/functional/runtime.html#

now has URL loading.

But the only way I could work with fetch is to have createX3DFromURL return another Promise which resolves to the retrieved X3D dom node. It actually makes sense and is rather easy to use:
```js
$element.runtime.createX3DFromURL(url)
        .then(function(x3d){
            $element.runtime.replaceWorld(x3d)
        });
```
There is probably a way to wrap this into a waiting, synchronous function, as well.

**Comment by coderextreme** [comment]
Ah, I see replaceScene.  I normally reload everything, parse the JSON twice etc.  It wasn’t always that way, but my application, X3DJSONLD, is getting a big split in it with some methods targeting X3DOM and some targeting X_ITE. Not sure what to do.   The base X3D JSON -> DOM remains the same. Working on creating a single source code for X3D JSON -> DOM.  I’ll probably create a superclass and an interface and subclasses, one for each type of browser. Whew!

I added scene.dom to X_ITE to retrieve the DOM from a parsed JSON in X_ITE.  I haven’t checked it in yet.  Is there a better way?

John

**Comment by andreasplesch** [comment]
https://rawgit.com/x3dom/x3dom/49eb3b0fd5966681f5e97e70f8be07c6d760295f/test/functional/runtime.html#

The createX3DFromJS works fine, not sure if there is anything else needed. The stripping in the example is only needed because it keeps reusing the same DOM onjects and x3dom modifies those each time they get loaded.

Perhaps unrelated, in order to avoid having an application to deal with promises, it may make sense to have a loadWorld(Url, opt) method which would be simply
```
.createX3DFromUrl(url,opt).
.then(function(x3d){
  .replaceWorld(x3d);
}
```
Since replaceWorld is not supposed to return anything anyways. .loadWorld would still return immediately. The loading and replacing happens async., but this can be documented. If the new world is needed to proceed, I think it fires a 'load' event when it is available.

**Comment by andreasplesch** [comment]
Hm. the lights accumulate when replacing worlds, eg. do not get reset. Digging.

**Comment by andreasplesch** [comment]
I found a solution to the lights but in the process started to think it may be better to simulate replaceWorld by cloning the existing x3d element first, then inserting the new scene, and then replacing the complete existing x3d element, and the doing a x3dom.reload. This destroys and creates a whole new x3d browser, and may be cause flicker but is the way x3dom is set up to load a new scene. I try this to see how well it works.

Turning fetch for createFromUrl into a synchronous call is difficult. It looks like only ES7 (or transpiling via babel) would do the trick via async/await. So renaming the method to createX3DFromURLPromise and returning a promise seems best for now.

**Comment by andreasplesch** [comment]
https://rawgit.com/x3dom/x3dom/7a30effb60b58c816ed450d3f51f1ebc6d7ddd53/test/functional/runtime.html#

uses a new replaceWorld which replaces the whole x3d browser. One difference is that the runtime.ready function is invoked after replacing which could be beneficial. Still have to test if the original x3d element css is preserved after replacement.

**Comment by coderextreme** [comment]
I will have to double check your changes.   I am currently moaning a bit
over carpal tunnel or arthritis.

John

**Comment by andreasplesch** [comment]
I generated a test build of x3dom-full.js etc. here:
http://x3dom-builds.surge.sh/latest/

**Comment by coderextreme** [comment]
Does that include loadJS?  I plan to separate out the individual calls in loadJS again and put a try catch around replaceWorld to see if I can get that to work.

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
No, it doesn’t  I note that there’s another loadJS, so  a rename is in order, after I try the try catch.

John

Sent from Mail for Windows 10

From: John Carlson
Sent: Tuesday, May 29, 2018 11:14 AM
To: x3dom/x3dom; x3dom/x3dom
Cc: Author
Subject: RE: [x3dom/x3dom] replaceWorld and JSON functions for Browser[WIP](#853)

Does that include loadJS?  I plan to separate out the individual calls in loadJS again and put a try catch around replaceWorld to see if I can get that to work.

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
I finally got this code working;

       function load_X3DOM_JSON(jsobj, selector, optionalURL) {
                var doc = document.querySelector(selector);
                if (doc.hasRuntime && doc.runtime.ready) {
                        /*
                        doc.runtime.loadJS(jsobj);
                        */
                            var x3d = doc.runtime.createX3DFromJS(jsobj, optionalURL)
                            if (x3d != null) {
                                    try {
                                        doc.runtime.replaceWorld(x3d);
                                    } catch (e) {
                                            console.error(e);
                                            alert(e);
                                    }
                            } else {
                                    x3dom.debug.logError("loadJS: could not fetch or parse " + jsobj);
                            }

                }
                // remove all text nodes in scripts (and fields too, sigh)
                $(selector+" Script").empty();
        }

I will update the pull request.

John

Sent from Mail for Windows 10

From: John Carlson
Sent: Tuesday, May 29, 2018 11:21 AM
To: x3dom/x3dom; x3dom/x3dom
Cc: Author
Subject: RE: [x3dom/x3dom] replaceWorld and JSON functions forBrowser[WIP](#853)

No, it doesn’t  I note that there’s another loadJS, so  a rename is in order, after I try the try catch.

John

Sent from Mail for Windows 10

From: John Carlson
Sent: Tuesday, May 29, 2018 11:14 AM
To: x3dom/x3dom; x3dom/x3dom
Cc: Author
Subject: RE: [x3dom/x3dom] replaceWorld and JSON functions for Browser[WIP](#853)

Does that include loadJS?  I plan to separate out the individual calls in loadJS again and put a try catch around replaceWorld to see if I can get that to work.

John

Sent from Mail for Windows 10

**Comment by coderextreme** [comment]
The pull request should now only contain comment updates (X3d -> X3D, edits).

Sent from Mail for Windows 10

From: John Carlson
Sent: Tuesday, May 29, 2018 9:40 PM
To: x3dom/x3dom; x3dom/x3dom
Cc: Author
Subject: RE: [x3dom/x3dom] replaceWorld and JSON functionsforBrowser[WIP](#853)

I finally got this code working;

       function load_X3DOM_JSON(jsobj, selector, optionalURL) {
                var doc = document.querySelector(selector);
                if (doc.hasRuntime && doc.runtime.ready) {
                        /*
                        doc.runtime.loadJS(jsobj);
                        */
                            var x3d = doc.runtime.createX3DFromJS(jsobj, optionalURL)
                            if (x3d != null) {
                                    try {
                                        doc.runtime.replaceWorld(x3d);
                                    } catch (e) {
                                            console.error(e);
                                            alert(e);
                                    }
                            } else {
                                    x3dom.debug.logError("loadJS: could not fetch or parse " + jsobj);
                            }

                }
                // remove all text nodes in scripts (and fields too, sigh)
                $(selector+" Script").empty();
        }

I will update the pull request.

John

Sent from Mail for Windows 10

From: John Carlson
Sent: Tuesday, May 29, 2018 11:21 AM
To: x3dom/x3dom; x3dom/x3dom
Cc: Author
Subject: RE: [x3dom/x3dom] replaceWorld and JSON functions forBrowser[WIP](#853)

No, it doesn’t  I note that there’s another loadJS, so  a rename is in order, after I try the try catch.

John

Sent from Mail for Windows 10

From: John Carlson
Sent: Tuesday, May 29, 2018 11:14 AM
To: x3dom/x3dom; x3dom/x3dom
Cc: Author
Subject: RE: [x3dom/x3dom] replaceWorld and JSON functions for Browser[WIP](#853)

Does that include loadJS?  I plan to separate out the individual calls in loadJS again and put a try catch around replaceWorld to see if I can get that to work.

John

Sent from Mail for Windows 10

**Pull request merged**
