### PR TITLE
importExportSupported

### PR DESCRIPTION
**Pull request by microaaron**
Support IMPORT/EXPORT node.
[https://github.com/x3dom/x3dom/issues/1166](https://github.com/x3dom/x3dom/issues/1166)

### CODE REVIEW

**Comment by microaaron** [comment]
[x3dom-full.debug.importExportSupported.js](https://raw.githubusercontent.com/microaaron/x3dom-full.debug.importExportSupported/main/x3dom-full.debug.importExportSupported.js)

**Comment by andreasplesch** [comment]
Looks good to me.

**Comment by andreasplesch** [comment]
Do you think you can address the formatting ? There is a strict check.

**Comment by microaaron** [comment]
test examples:
[ImportExample](https://jsitor.com/s3yvggZey)
[ImportFromProtoExample](https://jsitor.com/yon8B8392)
[ImportFromExternProtoExample](https://jsitor.com/QqD0EzYKh)

**Comment by andreasplesch** [comment]
Excellent. BTW, there is `githack.com`  which a lot of people use to get around github limitations on serving with the correct mime type: https://jsitor.com/FYLYZC_s7

Please add the tests to test/functional/exportimport/ .

Could you please also add a line to CHANGELOG.md ?  Just start a new section 'Version 1.8.3-dev' .

**Comment by andreasplesch** [comment]
Thanks !

**Pull request merged**
