### PR TITLE
First pass JSDoc fix-up

### PR DESCRIPTION
**Pull request by jamesleesaunders**
This PR is a simple first attempt fix-up of 2 files:
* Internals.js
* fields.js
It is by no means an extensive clean up and the doc blocks still need a lot more work, this is really just a first pass over some of the existing JSDoc to bring it more towards standards. There are still a number of functions which need blocks adding, and a number of blocks need @return @param adding/embellishing.

This is really more of a feeler PR - If this sort is something you are interested in, I am more than happy to progress further and go over each file in more detail. I would really love to contribute to x3dom in any way I can.

@andreasplesch I notice in your PR #867 you are also touching fields.js - hopefully there would be no conflict as you are simply adding a new function.

### CODE REVIEW

**Comment by jamesleesaunders** [comment]
Without wanting to get into a political formatting war, I was just wondering what the agreed curly braces format is in x3dom code? There are currently 2 variants:

```
function() {
   // foo
}

function()
{
   // foo
}
```

For what it is worth I prefer the first. I almost tidied these up but thought better if it as did not know agreed standard (and know full well how contentious this can be). Happy to leave as-is.

**Comment by andreasplesch** [comment]
Unfortunately, preferred formatting styles were never established, I think due to x3dom's history but it is a good idea to tidy things up. Thanks for doing this.
Personally, I do not really care too much where the braces are. Other active contributors may. @tsturm @mlimper ?
For indenting I developed a preference for four spaces, no tabs, for consistency across editors.

**Comment by mlimper** [comment]
> Personally, I do not really care too much where the braces are. Other active contributors may. @tsturm @mlimper ?

Hi, thanks for checking with me - I am not an active contributor any more, though.
If I would be, I wouldn't be concerned with braces as well, as long as there's one consistent style

**Comment by jamesleesaunders** [comment]
Any interest? Once this PR is approved I will get on and tidy up the JSDoc blocks in more detail. I’ll keep each PR restrained to only a file at a time.
Don’t worry if no time to review, it can wait.

**Comment by mlimper** [comment]
@andreasplesch do you have permissions to merge?

**Comment by andreasplesch** [comment]
James, is this ready to merge to then use other PRs ? Or do you want to keep this open ? The tests in the test folder are set up to work without building.

**Comment by jamesleesaunders** [comment]
Yeah merge it in now, I’ll open separate PRs for each trance of tidy-ups. Thanks.

**Pull request merged**
