### PR TITLE
Extend help shown in debug window

### PR DESCRIPTION
**Pull request by FrankBuchholz**
Add missing key commands to help info shown in debug window.

### CODE REVIEW

**Comment by andreasplesch** [comment]
home and end do not work that well because the browser also scrolls the page. Do you think these keys should still be listed ?

**Comment by FrankBuchholz** [comment]
I use a full screen X3DOM scene and have therefore no issues with scrolling... I guess this is the reason why I didn't realized potential conflicts. Anyway, the keys are active and you can use them to swap viewpoints.

I just found an old issue about these keys:
https://github.com/x3dom/x3dom/issues/777

I follow your advice.

**Comment by andreasplesch** [comment]
Did you want to make a change to this PR ?

**Comment by andreasplesch** [comment]
Let's keep it as is.

**Pull request merged**
