### PR TITLE
Fix for #655 - shading on clockwise TriangleSets

### PR DESCRIPTION
**Pull request by sevaa**

### CODE REVIEW

**Comment by andreasplesch** [comment]
Hm, something went wrong. The PR does not contain the fix. Do you want to give it another try ?

**Comment by sevaa** [comment]
Looks like on the first try I've pushed to my fork's master instead of the feature branch. The changes show up now, please try again.

**Comment by andreasplesch** [comment]
Looks good and should be ready to be merged.

**Comment by sevaa** [comment]
Um, should I merge it? I don't think I have the rights...

**Pull request merged**
