### PR TITLE
improve text quality

### PR DESCRIPTION
**Pull request by andreasplesch**
by oversampling by a factor of two but keeping the textured rectangle the same size. Addresses issue #541 . It would be straightforward to make the oversampling factor a custom field of the text node (default 1 or 2) for backwards compatibility.

### CODE REVIEW

**Comment by mlimper** [comment]
Nice, thanks - I would agree to your proposal of making this a custom field of the text node.
Could you add the field before we merge this one?

**Comment by andreasplesch** [comment]
Will do. I would prefer to set the default for this custom field ('quality') to 2. I cannot think of a case where the larger texture would be a problem, and it does look much better. Any reason not to set it to 2 ?
I will also bracket the max. to 10 to avoid extremely large textures. And the min. to 0.5.

**Comment by andreasplesch** [comment]
I added a 'quality' field to the FontStyle node with a default of 2.0 and enforced bracketing to 0.5 and 10. FontStyle seemed more appropriate than Text since it really is a style option. I updated the two examples referenced in issue #541 to use the custom quality factors. Let me know if there is anything else.

**Comment by mlimper** [comment]
That's great, thanks a lot for this contribution.

**Comment by andreasplesch** [comment]
Glad to  contribute.

**Pull request merged**
